--- 
apiVersion: v1
kind: Service
metadata: 
  name: sdsapp-statefull-service
spec: 
  selector: 
    run: sdsapp-statefull
    ports: 
      - name: sdsapp-statefull
        protocol: TCP
        run: sdsapp-statefull
        port: 8080
        targetPort: 3000
    type: NodePort