--- 
apiVersion: apps/v1
kind: Deployment
metadata: 
  name: sdsapp-stateless
spec: 
  replicas: 2
  selector: 
    matchLabels: 
      run: sdsapp-stateless
  template: 
    metadata: 
      labels: 
        run: sdsapp-stateless
    spec: 
      containers: 
        - image: stefds/sdsapp
          name: sdsapp