--- 
apiVersion: apps/v1
kind: Deployment
metadata: 
  name: sdsapp-statefull
spec: 
  replicas: 2
  selector: 
    matchLabels: 
      run: sdsapp-statefull
  template: 
    metadata: 
      labels: 
        run: sdsapp-statefull
    spec: 
      containers: 
        - image: stefds/sdsapp
          name: sdsapp
          volumeMounts:
          - name: sdsapp-data
            mountPath: "/usr/src/app/data"
      volumes:
      - name: sdsapp-data
        persistentVolumeClaim:
          claimName: sdsapp-pvc