--- 
apiVersion: apps/v1
kind: Deployment
metadata: 
  name: sdsapp-statefull
spec: 
  replicas: 1
  template: 
    metadata: 
      labels: 
        app: sdsapp-statefull
    spec: 
      containers: 
        - name: sdsapp
          image: stefds/sdsapp
          volumeMounts:
          - name: sdsapp-data
            mountPath: "/usr/src/app/data"
      volumes:
      - name: sdsapp-data
        persistentVolumeClaim:
          claimName: sdsapp-pvc