--- 
apiVersion: v1
kind: Service
metadata: 
  name: sdsapp-service
spec: 
  selector: 
    run: sdsapp-stateless
    ports: 
      - name: sdsapp-stateless
        protocol: TCP
        run: sdsapp-stateless
        port: 8080
        targetPort: 3000
    type: NodePort