---
apiVersion: kubedirector.hpe.com/v1beta1
kind: KubeDirectorApp
metadata:
  name: sdsapp-kubedir
spec:
  systemdRequired: true
  defaultPersistDirs:
  - "/usr"
  - "/data"
  defaultEventList:
  - configure
  - addnodes
  - delnodes
  config:
    roleServices:
    - serviceIDs:
      - http
      roleID: sdsapp-kubedir
    selectedRoles:
    - sdsapp-kubedir
  label:
    name: sdsapp-kubedir
    description: StefDS Statefull application example  
  defaultImageRepoTag: docker.io/stefds/sdsapp:latest
  defaultConfigPackage: 
  distroId: stefds/sdsapp
  version: 'latest'
  configSchemaVersion: 1
  services:
  - endpoint:
      port: 80
      isDashboard: true
    id: http
    label:
      name: HTTP
  roles:
  - cardinality: 1+
    id: sdsapp-kubedir