---
apiVersion: app/v1
kind: Service
metadata: 
  name: sdsapp-service
spec: 
  selector: 
    port: 8080
    ports: 
      - 
      name: sdsapp
    protocol: TCP
    run: sdsapp
    targetPort: 3000
    type: NodePort