--- 
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sdsapp
spec:
  replicas: 2
  selector:
    matchLabels:
      run: sdsapp
  template:
    metadata:
      labels:
        run: sdsapp
    spec: 
      containers:
        - name: sdsapp
          image: stefds/sdsapp
---
apiVersion: v1
kind: Service
metadata:
  name: sdsapp-service
  labels: 
    hpecp.hpe.com/hpecp-internal-gateway: "true"
spec:
  selector:
    run: sdsapp
  ports:
  - name: http
    protocol: TCP
    port: 8088
    targetPort: 3000
  type: NodePort
