apiVersion: v1
kind: Service
metadata:
  name: sdsapp-stateless-service
  labels: 
    hpecp.hpe.com/hpecp-internal-gateway: "true"
spec:
  selector:
    run: sdsapp-stateless
  ports:
  - name: sdsapp-stateless
    protocol: TCP
    port: 8088
    targetPort: 3000
  type: NodePort
